# DigitalOcean App Platform Spec
# Use this file for faster deployment

name: flatmates-api
region: nyc

services:
  - name: api
    github:
      repo: YOUR_GITHUB_USERNAME/flatmates-app
      branch: main
      deploy_on_push: true

    source_dir: /backend

    build_command: pip install -r requirements.txt
    run_command: uvicorn app.main:app --host 0.0.0.0 --port 8080

    http_port: 8080

    instance_count: 1
    instance_size_slug: basic-xxs

    health_check:
      http_path: /health
      initial_delay_seconds: 60
      period_seconds: 30
      timeout_seconds: 15
      success_threshold: 1
      failure_threshold: 5

    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET

      - key: SECRET_KEY
        scope: RUN_TIME
        type: SECRET

      - key: ALGORITHM
        value: HS256
        scope: RUN_TIME

      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "10080"
        scope: RUN_TIME

      - key: BACKEND_CORS_ORIGINS
        value: '["*"]'
        scope: RUN_TIME

      - key: GOOGLE_CLIENT_ID
        scope: RUN_TIME
        type: SECRET

      - key: GOOGLE_CLIENT_SECRET
        scope: RUN_TIME
        type: SECRET

      - key: OPENAI_API_KEY
        scope: RUN_TIME
        type: SECRET

      - key: GEMINI_API_KEY
        scope: RUN_TIME
        type: SECRET

databases:
  - name: flatmates-db
    engine: PG
    version: "15"
    production: true
    cluster_name: flatmates-db-cluster
