name: Full CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      mobile: ${{ steps.filter.outputs.mobile }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: Check for changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'
              - '.github/workflows/backend-ci.yml'
              - '.github/workflows/full-ci.yml'
            mobile:
              - 'mobile/**'
              - '.github/workflows/mobile-ci.yml'
              - '.github/workflows/full-ci.yml'

  backend-ci:
    needs: detect-changes
    if: needs.detect-changes.outputs.backend == 'true'
    uses: ./.github/workflows/backend-ci.yml

  mobile-ci:
    needs: detect-changes
    if: needs.detect-changes.outputs.mobile == 'true'
    uses: ./.github/workflows/mobile-ci.yml

  all-tests-passed:
    needs: [backend-ci, mobile-ci]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Check all jobs
        run: |
          echo "Backend CI: ${{ needs.backend-ci.result }}"
          echo "Mobile CI: ${{ needs.mobile-ci.result }}"
          
          if [[ "${{ needs.backend-ci.result }}" == "failure" ]] || [[ "${{ needs.mobile-ci.result }}" == "failure" ]]; then
            echo "One or more CI jobs failed"
            exit 1
          fi
          
          echo "All CI jobs passed!"
